spring:
  application:
    name: sherlockops

  datasource:
    url: jdbc:postgresql://localhost:5432/sherlockops
    username: sherlock
    password: sherlock

  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false

  flyway:
    enabled: true